apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pricebox-landpage-app
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - backend:
          serviceName: pricebox-landpage-app-clusterip
          servicePort: 80
        # path: /api/some-route